### ISSUE TITLE
Creating app fails

### ISSUE THREAD

**Issue by SomethingGeneric** [hugojosefson/proxmox-create-docker-ct#1]
While trying to create an app, with the PVE debian 12 template, I get:
![image](https://github.com/hugojosefson/proxmox-create-docker-ct/assets/12242178/ef133646-4dce-4e25-91c4-e6e992fdcce6)

**Comment by hugojosefson** [comment]
Hi Matt! (Wow, a user! :+1: )

It seems I hadn't handled that error very gracefully. But now I have added a specific error message for missing template install scripts. Try re-installing, then running the command again. The error should at least be more clear now :)

How the tool works, is that for every template, there has to be an install script. They are in this directory, named like `<distro>-<version>-install`:

https://github.com/hugojosefson/proxmox-create-docker-ct/tree/main/usr_local_bin/create-docker-ct-files/template

You should find them locally in `/usr/local/bin/create-docker-ct-files/template/`.

I have not made one for Debian 12. I think it should be fairly similar to https://github.com/hugojosefson/proxmox-create-docker-ct/blob/main/usr_local_bin/create-docker-ct-files/template/ubuntu-2204-install, so you might try and copy that, and possibly modify some things.

Please let me know if you get a `debian-12-install` script to work, because then we can make it available here!

**Comment by hugojosefson** [comment]
You might find it useful to set environment variable `VERBOSE=true`, like so:

```sh
VERBOSE=true create-docker-ct npm debian-12-standard_12.0-1_amd64.tar.zst
```

Then you will see more exact internally executed commands, and their results.

**Comment by hugojosefson** [comment]
I have added debian-12 now, using the same install script as ubuntu 22.04. Please try it, and report if it works for you, or any errors you get!
